name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17' # Hoặc phiên bản Java mà bạn sử dụng
        distribution: 'temurin' # Hoặc 'adopt' nếu bạn muốn

    - name: Build with Maven
      run: mvn clean test

    - name: Install Allure
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.30.0/allure-2.30.0.zip
        unzip allure-2.30.0.zip -d allure
        sudo ln -s $GITHUB_WORKSPACE/allure/allure-2.30.0/bin/allure /usr/local/bin/allure

    - name: Generate Allure report
      run: mvn allure:report

    - name: Serve Allure report
      run: mvn allure:serve

    - name: Upload Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: target/allure-results
